version: "3.8"
services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - data:/data
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=admin
      - MONGODB_INITB_ROOT_PASSWORD=1doi3patru5sase7opt
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMIN_USERNAME=admin
      - ME_CONFIG_MONGODB_ADMIN_PASSWORD=1doi3patru5sase7opt
      - ME_CONFIG_MONGODB_SERVER=mongodb
volumes:
  data: {}
networks:
  default:
    name: mongodb_network